VDS-546: View product list of the part
VirtoCommerce/vc-module-demo-features pull request #48
Opened 2021-01-14 08:41 UTC by ilyawzrd

2021-01-14 10:00 UTC, pushnitsa requested changes

2021-01-14 10:00 UTC, pushnitsa commented on src/VirtoCommerce.DemoSolutionFeaturesModule.Web/Scripts/blades/part-product-list.js
> +                        bladeNavigationService.showConfirmationIfNeeded(true, true, blade, deleteProducts(selectedNodesId), ()=>{}, "demoSolutionFeaturesModule.dialogs.default-product-delete.title",
I guess that pass successful callback should be wrapped with arrow function, like:
bladeNavigationService.showConfirmationIfNeeded(true, true, blade, **() => { deleteProducts(selectedNodesId); }**, ()=>{}, "demoSolutionFeaturesModule.dialogs.default-product-delete.title", "demoSolutionFeaturesModule.dialogs.default-product-delete.message");

2021-01-14 10:00 UTC, pushnitsa commented on src/VirtoCommerce.DemoSolutionFeaturesModule.Web/Scripts/blades/part-product-list.js
> +                bladeNavigationService.showConfirmationIfNeeded(true, true, blade, deleteProduct(selectedNodeId), ()=>{}, "demoSolutionFeaturesModule.dialogs.default-product-delete.title", "demoSolut
Wrap deleteProduct with arrow function

2021-01-14 10:00 UTC, pushnitsa commented on src/VirtoCommerce.DemoSolutionFeaturesModule.Web/Scripts/blades/part-product-list.tpl.html
> +        <i class="fa fa-ellipsis-v"></i>
Add aria-hidden="true" attribute

2021-01-14 10:00 UTC, pushnitsa commented on src/VirtoCommerce.DemoSolutionFeaturesModule.Web/Scripts/blades/part-product-list.tpl.html
> +                       <i class="menu-ico fa fa-check"></i> {{'demoSolutionFeaturesModule.blades.part-product-list.context-menu.default' | translate}}
aria-hidden="true"

2021-01-14 10:00 UTC, pushnitsa commented on src/VirtoCommerce.DemoSolutionFeaturesModule.Web/Scripts/blades/part-product-list.tpl.html
> +                       <i class="menu-ico fa fa-trash-o"></i> {{'platform.commands.delete' | translate}}
aria-hidden="true"

2021-01-14 10:04 UTC, ilyawzrd commented on src/VirtoCommerce.DemoSolutionFeaturesModule.Web/Scripts/blades/part-product-list.tpl.html
> +                       <i class="menu-ico fa fa-check"></i> {{'demoSolutionFeaturesModule.blades.part-product-list.context-menu.default' | translate}}
done

2021-01-14 10:04 UTC, ilyawzrd commented on src/VirtoCommerce.DemoSolutionFeaturesModule.Web/Scripts/blades/part-product-list.tpl.html
> +        <i class="fa fa-ellipsis-v"></i>
done

2021-01-14 10:04 UTC, ilyawzrd commented on src/VirtoCommerce.DemoSolutionFeaturesModule.Web/Scripts/blades/part-product-list.tpl.html
> +                       <i class="menu-ico fa fa-trash-o"></i> {{'platform.commands.delete' | translate}}
done

2021-01-14 10:09 UTC, ilyawzrd commented on src/VirtoCommerce.DemoSolutionFeaturesModule.Web/Scripts/blades/part-product-list.js
> +                        bladeNavigationService.showConfirmationIfNeeded(true, true, blade, deleteProducts(selectedNodesId), ()=>{}, "demoSolutionFeaturesModule.dialogs.default-product-delete.title",
done

2021-01-14 10:09 UTC, ilyawzrd commented on src/VirtoCommerce.DemoSolutionFeaturesModule.Web/Scripts/blades/part-product-list.js
> +                bladeNavigationService.showConfirmationIfNeeded(true, true, blade, deleteProduct(selectedNodeId), ()=>{}, "demoSolutionFeaturesModule.dialogs.default-product-delete.title", "demoSolut
done

2021-01-14 10:22 UTC, pushnitsa requested changes

2021-01-14 10:22 UTC, pushnitsa commented on src/VirtoCommerce.DemoSolutionFeaturesModule.Web/Scripts/blades/part-product-list.js
> +        $scope.canSave = () => {
() => isDirty();

2021-01-14 10:22 UTC, pushnitsa commented on src/VirtoCommerce.DemoSolutionFeaturesModule.Web/Scripts/blades/part-product-list.js
> +            blade.currentEntity.partItems = _.filter(blade.currentEntity.partItems, (part) => {
(part) => part.itemId !== selectedNodeId

2021-01-14 10:30 UTC, ilyawzrd commented on src/VirtoCommerce.DemoSolutionFeaturesModule.Web/Scripts/blades/part-product-list.js
> +        $scope.canSave = () => {
done

2021-01-14 10:30 UTC, ilyawzrd commented on src/VirtoCommerce.DemoSolutionFeaturesModule.Web/Scripts/blades/part-product-list.js
> +            blade.currentEntity.partItems = _.filter(blade.currentEntity.partItems, (part) => {
done

2021-01-14 14:27 UTC, ilyawzrd commented
![Снимок экрана 2021-01-14 в 16 26 47](https://user-images.githubusercontent.com/22875828/104603695-557fa580-5685-11eb-9573-da98547ea37c.png)

2021-01-18 10:12 UTC, pushnitsa approved these changes

2021-01-18 11:18 UTC, ilyawzrd commented
Closed. All changes now are part of https://github.com/VirtoCommerce/vc-module-demo-features/pull/51

2021-01-18 11:18 UTC, closed without merging