VDS-904 Implement indexation of members User Groups (member tags)
VirtoCommerce/vc-module-demo-features pull request #71
Opened 2021-02-15 10:11 UTC by trueboroda

Also implement turning on logic by feature flag state.

2021-02-15 10:57 UTC, pushnitsa requested changes

2021-02-15 10:57 UTC, pushnitsa commented on src/VirtoCommerce.DemoSolutionFeaturesModule.Web/Module.cs
> +            featureStorage.TryAddFeature(ModuleConstants.Features.ConfigurableProduct, true);
Please specify exactly the module in which constants are used.

2021-02-15 10:57 UTC, pushnitsa commented on src/VirtoCommerce.DemoSolutionFeaturesModule.Web/Module.cs
> +            var documentIndexingConfigurations = appBuilder.ApplicationServices.GetRequiredService<IEnumerable<IndexDocumentConfiguration>>();
Add empty line

2021-02-15 10:57 UTC, pushnitsa commented on src/VirtoCommerce.DemoSolutionFeaturesModule.Data/Services/Customer/DemoMemberService.cs
> +            var userGroupsInheritanceFeatureIsEnabled = await _featureManager.IsEnabledAsync(ModuleConstants.Features.UserGroupsInheritance);
Add empty line

2021-02-15 11:50 UTC, pushnitsa approved these changes

2021-02-17 09:43 UTC, closed without merging

2021-02-17 09:44 UTC, trueboroda commented
It will bring with this PR https://github.com/VirtoCommerce/vc-module-demo-features/pull/73